#!/usr/bin/env python3

import os
import argparse

os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide"
import pygame

import shutil
import tempfile

def play_audio(filename):
    pygame.mixer.init()
    pygame.mixer.music.load(filename)
    pygame.mixer.music.play()
    while pygame.mixer.music.get_busy():
        pygame.time.Clock().tick(10)
    pygame.mixer.quit()

def main():
    parser = argparse.ArgumentParser(description='Daan TTS using Docker and Piper.')
    parser.add_argument('text', type=str, help='Text to convert to speech.')
    parser.add_argument('--output', type=str, help='Save the output to a file. If not provided, play audio directly.')
    parser.add_argument('--play', action='store_true', help='Play the audio after saving.')

    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as tmpdir:
        command = f'docker run -e INPUT_STRING="{args.text}" -v {tmpdir}:/output daan'
        os.system(command)

        # Temporary path to the output.wav
        temp_output_path = os.path.join(tmpdir, "output.wav")

        if args.output:
            shutil.move(temp_output_path, args.output)
            
            if args.play:
                play_audio(args.output)
        else:
            play_audio(temp_output_path)

if __name__ == '__main__':
    main()
